name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or whatever your primary branch is

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # If you want to build/transform files first, add steps here.
      # For your current setup, it's a direct copy.

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Assuming your index.html and CSVs are in the root
          # If your files are in a 'dist' or 'docs' folder after a build step:
          # publish_dir: ./dist